logLevel = "debug" # "debug" | "warn" | "error"
telemetry = false


# N.B. Bun does not execute lifecycle scripts of installed dependencies,
# because it can be very unsafe and should not be needed in most cases.
[install]
# Set exact version for dependencies (X.Y.Z instead of ^X.Y.Z in package.json)
exact = true
# No indirect optional dependencies. They should be explicitly added if needed.
optional = false
peer = false

# Delay package adoption to give the community time to flag malicious or broken versions.
minimumReleaseAge=10080  # 10080m = 7d

# Give in priority from the lock file.
# Fail over conflicts with dependencies to force verifying updates to the lockfile.
frozenLockfile = false

# Use binary format for the lockfile. Mostly to reduce noise in diffs.
saveTextLockfile = false

[test]
root = "src"

coverage = true
coveragePathIgnorePatterns = [
  "**/*.spec.ts",
  "**/*.test.ts",
  "**/__tests___/**",
  # Ignore root config files
  "*.config.js"
]

# Only show details for failed tests
onlyFailures = true
